
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Info_estacoes extends javax.swing.JFrame {

    /**
     * Creates new form Info_estacoes
     */
    public Info_estacoes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Comodidades e serviços");
        cmb_info_estacoes.addItem("Selecione a estação");
        cmb_info_estacoes.addItem("BRÁS");
        cmb_info_estacoes.addItem("MOOCA");
        cmb_info_estacoes.addItem("IPIRANGA");
        cmb_info_estacoes.addItem("TAMANDUATEÍ");
        cmb_info_estacoes.addItem("SÃO CAETANO");
        cmb_info_estacoes.addItem("UTINGA");
        cmb_info_estacoes.addItem("PREFEITO SALADINO");
        cmb_info_estacoes.addItem("SANTO ANDRÉ");
        cmb_info_estacoes.addItem("CAPUAVA");
        cmb_info_estacoes.addItem("MAUÁ");
        cmb_info_estacoes.addItem("GUAPITUBA");
        cmb_info_estacoes.addItem("RIBEIRÃO PIRES");
        cmb_info_estacoes.addItem("RIO GRANDE DA SERRA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txt_comodidades = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_servicos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_info_estacoes = new javax.swing.JComboBox<>();

        txt_comodidades.setColumns(20);
        txt_comodidades.setRows(5);
        jScrollPane2.setViewportView(txt_comodidades);

        txt_servicos.setColumns(20);
        txt_servicos.setRows(5);
        jScrollPane4.setViewportView(txt_servicos);

        jLabel1.setText("Comodidades:");

        jLabel2.setText("Serviços:");

        cmb_info_estacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_info_estacoesMouseClicked(evt);
            }
        });
        cmb_info_estacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_info_estacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmb_info_estacoes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(250, 250, 250))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(cmb_info_estacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_info_estacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_info_estacoesMouseClicked
       
    }//GEN-LAST:event_cmb_info_estacoesMouseClicked

    private void cmb_info_estacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_info_estacoesActionPerformed
        try{
            int index = cmb_info_estacoes.getSelectedIndex();
            Interface_Trem objeto = (Interface_Trem) Naming.lookup("rmi://localhost:1234/trem");
            txt_comodidades.setText((objeto.Comodidades(index)).toString().replace("[", " ").replace(",", "").replace("]", " "));
            txt_servicos.setText((objeto.Servicos(index)).toString().replace("[", " ").replace(",", "").replace("]", " "));
        }catch (MalformedURLException | RemoteException | NotBoundException e ){
            System.out.println("Erro"+e.toString());
        }
    }//GEN-LAST:event_cmb_info_estacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info_estacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info_estacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info_estacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info_estacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info_estacoes().setVisible(true);
            }
        });
         
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cmb_info_estacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextArea txt_comodidades;
    public javax.swing.JTextArea txt_servicos;
    // End of variables declaration//GEN-END:variables

}
